<?php
/**
 * Created by PhpStorm.
 * User: Anatoli
 * Date: 30.09.2016
 * Time: 18:08
 */ ?>
<div class="manager-widget">

    <div class="block-title">
        <strong><span><?= $this->__('Manager') ?></span></strong>
    </div>

    <div>
        <?php foreach($managers as $manager):?>
            <div>
                    <h4><?= $manager->getName()?></h4>
                <?php if($manager->getPhoto()):?>
                    <p><img src="/media/<?=$manager->getPhoto()?>" title="<?php echo
                        $this->escapeHtml($manager->getName()); ?>" border="0" width="100%"/></p>
                <?php endif;?>
                <?php if($manager->getSecondName()):?>
                    <p><label><?= $this->__('Name') ?>:&nbsp </label><?= $manager->getSecondName()?></p>
                <?php endif;?>
                <?php if($manager->getTelephone()):?>
                    <p><label><?= $this->__('Phone') ?>:&nbsp </label><?= $manager->getTelephone()?></p>
                <?php endif;?>
                <?php if($manager->getEmail()):?>
                    <p><label><?= $this->__('Email') ?>:&nbsp </label><?= $manager->getEmail()?></p>
                <?php endif;?>
            </div>
        <?php endforeach;?>
    </div>
</div>